accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('follow/<str:username>', views.follow, name='follow'),
    path('unfollow/<str:username>', views.unfollow, name='unfollow'),
    path('<str:username>/_saved/', views.profile, name='profile'),
    path('settings/edit-profile/', views.edit_profile, name='edit_profile'),
    path('activate/<str:uidb64>/<str:token>/',
         views.activate_email, name='activate_email'),
    path('verify_email/', views.verify_email, name='verify_email'),
]

boards/urls.py
from django.urls import path

from . import views

app_name = 'boards'

urlpatterns = [
    path('create/', views.create_board, name='create_board'),
    path('<str:username>/<str:board_name>/', views.board_detail, name='board_detail'),
    path('<int:id>/', views.edit_board, name='edit_board'),
    path('save/<int:id>', views.save_to_board, name='save_to_board'),
    path('remove/<int:pin_id>/<int:board_id>/', views.remove_from_board, name='remove_from_board'),
]

pins/urls.py
from unicodedata import name
from django.urls import path

from . import views

app_name = 'pins'

urlpatterns = [
    path('create/', views.create_pin, name='create_pin'),
    path('edit/<int:id>', views.edit_pin, name='edit_pin'),
    path('delete/<int:id>', views.delete_pin, name='delete_pin'),
    path('comment/<int:id>', views.add_comment, name='add_comment'),
    path('delete-comment/<int:id>', views.delete_comment, name='delete_comment'),
    path('pin/<int:id>/', views.pin_detail, name='pin_detail'),
    path('<str:username>/created/', views.created_pins, name='created_pins'),
]

pinterest_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pinterest.urls', namespace='pinterest')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('boards/', include('boards.urls', namespace='boards')),
    path('pins/', include('pins.urls', namespace='pins')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser

from .managers import UserManager


class User(AbstractBaseUser):
    email = models.EmailField(max_length=100, unique=True)
    username = models.CharField(max_length=150, unique=True)    
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)


    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']


    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(default='profiles/default.png', upload_to='profiles')
    about = models.TextField()
    fname = models.CharField(max_length=300)
    lname = models.CharField(max_length=300)
    pronouns = models.CharField(max_length=100)
    website = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.user.username} Profile'


class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followers')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')

    def __str__(self):
        return f'{self.follower} is following {self.following}'

accounts/forms.py
from django import forms
from django.forms import ModelForm

from .models import Profile


class UserLoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control rounded-pill', 'placeholder': 'username'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control rounded-pill', 'placeholder': 'password'}
        )
    )


class UserRegistrationForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control rounded-pill', 'placeholder': 'email'}
        )
    )
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control rounded-pill', 'placeholder': 'username'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control rounded-pill', 'placeholder': 'password'}
        )
    )


class EditProfileForm(ModelForm):
    photo = forms.ImageField(required=False, widget=forms.FileInput)
    
    class Meta:
        model = Profile
        fields = ['photo', 'about', 'fname', 'lname', 'pronouns', 'website']

    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if visible.name == 'about':
                visible.field.widget.attrs['class'] = 'edit-profile-input form-control about-input'
            else:
                visible.field.widget.attrs['class'] = 'edit-profile-input form-control rounded-pill'
        

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.sites.shortcuts import get_current_site

from boards.forms import CreateBoardForm
from .forms import UserRegistrationForm, UserLoginForm, EditProfileForm
from .models import User, Follow
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages

from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth import get_user_model

User = get_user_model()


def user_register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            check_user = User.objects.filter(
                Q(username=data['username']) | Q(email=data['email'])
            )
            if not check_user:
                # create a new user with is_active=False
                user = User.objects.create_user(
                    data['email'], data['username'], data['password']
                )
                user.is_active=False
                user.save()
                # generate a token for email verification
                token = default_token_generator.make_token(user)
                # send email with verification link
                subject = 'Activate Your Account'
                message = render_to_string('activate_email.html', {
                    'user': user,
                    'domain': get_current_site(request),
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': token,
                })
                send_mail(
                    subject, message, 'noreply@example.com', [data['email']], fail_silently=False,
                )
                # redirect to the verification page
                messages.success(request, 'Thank you for signing up!\nPlease check your email and follow the instructions to activate your account.')
                return redirect('accounts:user_login')
    else:
        form = UserRegistrationForm()
    context = {'title': 'Signup', 'form': form}
    return render(request, 'register.html', context)


def activate_email(request, uidb64, token):
    try:
        # decode user id from uidb64 string
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(
            request, 'Your account has been activated!\n You can now log in using your credentials.')

        return redirect('accounts:user_login')

    else:
        messages.success(
            request, 'Sorry, the activation link is invalid or has expired.\n Please request a new activation link or contact the support team for assistance.')

        return redirect('accounts:user_login')

    

def verify_email(request):
    return render(request, 'verify_email.html')

def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(
                request, username=data['username'], password=data['password']
            )
            if user is not None:
                login(request, user)
                return redirect('pinterest:home')
            else:
                return redirect(request.META.get('HTTP_REFERER'))
    else:
        form = UserLoginForm()
    context = {'title':'Login', 'form': form}
    return render(request, 'login.html', context)


def user_logout(request):
    logout(request)
    return redirect('accounts:user_login')


@login_required
def follow(request, username):
    user = get_object_or_404(User, username=username)
    check_user = Follow.objects.filter(follower=request.user, following=user)
    if user == request.user:
        raise Http404
    elif check_user.exists():
        raise Http404
    else:
        follow = Follow.objects.create(follower=request.user, following=user)
        follow.save()
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def unfollow(request, username):
    user = get_object_or_404(User, username=username)
    following = Follow.objects.filter(following=user).delete()
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def profile(request, username):
    user = get_object_or_404(User, username=username)
    boards = user.board_user.all()
    is_following = request.user.followers.filter(following=user).first()
    create_board_form = CreateBoardForm()
    context = {
        'user': user,
        'boards':boards,
        'is_following': is_following,
        'create_board_form':create_board_form
    }
    return render(request, 'profile.html', context)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        if form.is_valid():
            form.save()
            return redirect('accounts:profile', request.user.username)
    else:
        form = EditProfileForm(instance=request.user.profile)
    context = {'title': 'Edit Profile', 'form': form}
    return render(request, 'edit_profile.html', context)

accounts/templates/activate_email.html
Hello {{ user.username }},
 Please click on the link below to activate your account:
 http://{{ domain }}{% url 'accounts:activate_email' uidb64=uid token=token %}
 Thank you.
 Best regards,
The Team

accounts/templates/activate_fail.html
{% extends 'login.html' %}
 {% block content %}
    <h1>Sorry, the activation link is invalid or has expired.</h1>
    <p>Please request a new activation link or contact the support team for assistance.</p>
{% endblock %}

accounts/templates/activate_success.html
{% extends 'login.html' %}
 {% block content %}
    <h1>Your account has been activated!</h1>
    <p>You can now log in using your credentials.</p>
{% endblock %}

accounts/templates/edit_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row">
        <div class="col-md-2 pt-4 me-5 pb-5">
            <p class="text-black"><b>Public profile</b></p>
            <p class="text-black"><b>Account settings</b></p>
        </div>
        <div class="col-md-8 ps-5 pe-5 pt-3 pb-5">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h2 class="text-black"><b>Public Profile</b></h2>
                <p class="mb-4" >People visiting your profile will see the following info</p>
                <div class="row mt-1">
                    <div class="col-md-1 me-4">
                        <label for="">Photo</label>
                        <img 
                            style="object-fit: cover;" 
                            width="80"
                            height="80" 
                            class="rounded-circle" 
                            src="{{ request.user.profile.photo.url }}" 
                        />
                    </div>
                    <div class="col-md-5 mt-5 mb-4">
                        {{ form.photo }}
                    </div>
                    <div class="col-md-3 mt-5 mb-4"></div>
                    <div class="col-md-4 mt-3">
                        <label class="mb-1" for="">First Name</label>
                        {{ form.fname }}
                    </div>
                    <div class="col-md-4 mt-3">
                        <label class="mb-1" for="">Last Name</label>
                        {{ form.lname }}
                    </div>
                    <div class="col-md-8 mt-3">
                        <label class="mb-1" for="">About</label>
                        {{ form.about }}
                    </div>
                    <div class="col-md-8 mt-3">
                        <label class="mb-1" for="">Pronouns</label>
                        {{ form.pronouns }}
                    </div>
                    <div class="col-md-8 mt-3">
                        <label class="mb-1" for="">Website</label>
                        {{ form.website }}
                    </div>
                    <div class="col-md-8 mt-3">
                        <button type="submit" class="red-btn btn ps-4 pe-4 pt-3 pb-3 text-white"><b>Save</b></button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

accounts/templates/first_header.html
<div class="p-3 bg-white first-header">
    <div class="d-flex flex-wrap align-items-center justify-content-center">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Pinterest_Logo.svg/1200px-Pinterest_Logo.svg.png" width="120" height="33" alt="">
        </a>
        <ul class="nav ms-5 col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0"></ul>
        <div class="dropdown text-end">
        <a class="text-decoration-none text-black me-4" href="#"><b>About</b></a>
        <a class="text-decoration-none text-black me-4" href="#"><b>Business</b></a>
        <a class="text-decoration-none text-black me-5" href="#"><b>Blog</b></a>
        <a href="{% url 'accounts:user_login' %}" id="loginBtn" class="red-btn btn text-white "><b>Login</b></a>
        <a href="{% url 'accounts:user_register' %}" class="main-btn btn text-black ms-3"><b>Sign Up</b></a>
        </div>
    </div>
</div>

accounts/templates/login.html
{% load static %}
<!DOCTYPE html>
<head>
    <!-- bootstrap css cdn -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Pinterest</title>
</head>

{% include 'first_header.html' %}
<body class="login-bg" style="height: 100vh;">


    <div class="modal-content ps-5 pb-5 pe-5">
        <h3 class="mt-4 mb-3"><b>Login</b></h3>
        <div class="row">
            {% if messages %}
                {% for message in messages %}
                    <center><p class="text-center text-danger">{{ message }}</p></center>
                {% endfor %}
            {% endif %}
            <form method="post">
                {% csrf_token %}
                <div class="">
                    {{ form.username }}
                </div>
                <div class="mt-2">
                    {{ form.password }}
                </div>
                <input class="modal-red-btn btn text-white mt-3 w-100" type="submit" value="Login">
            </form>
            <small class="text-muted mt-3">
                New Here? <a class="text-decoration-none" href="{% url 'accounts:user_register' %}">Create account</a>
            </small>
        </div>
    </div>
</body>
</html>

accounts/templates/profile.html
{% extends "base.html" %}
{% block content %}
<div class="col-md-1"></div>
<div class="col-md-10 text-center">
    {% if request.user == user %}
    <!-- plus icon | create board and pin dropdown menu -->
    <div class="dropdown">
        <a style="float: right; margin-top: 430px;" href="#"class="d-block link-dark text-decoration-none" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" class="gUZ pBj U9O kVc" height="20" width="20" viewBox="0 0 24 24" aria-hidden="true" aria-label="" role="img">
                <path d="M22 10h-8V2a2 2 0 0 0-4 0v8H2a2 2 0 0 0 0 4h8v8a2 2 0 0 0 4 0v-8h8a2 2 0 0 0 0-4" fill="#111111" stroke-width="0px"></path>
            </svg>
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownUser1">
            <li><a id="createBoardBtn" class="dropdown-item" href="#">Create Board</a></li>
            <li><a class="dropdown-item" href="{% url 'pins:create_pin' %}">Create Pin</a></li>
        </ul>
    </div>
    {% endif %}
    <!-- user public information -->
    <!-- user photo -->
    <img style="object-fit: cover;" width="150" height="150" class="rounded-circle" src="{{ user.profile.photo.url }}" alt="">
    <!-- Username or first and last name -->
    <h1 class="text-black"><b>{% if user.profile.fname %}{{ user.profile.fname }} {{ user.profile.lname }}{% else %}{{ user.username }}{% endif %}</b></h1>
    <!-- username and pronouns -->
    <p class="text-muted">@{{ user.username }} . {{ user.profile.pronouns }}</p>
    <!-- website link and about -->
    <p><b><a class="text-black text-decoration-none" href="http://{{user.profile.website}}">{{ user.profile.website }}</a></b> . {{ user.profile.about }}</p>
    <!-- following and followers count -->
    <span><b>{{ user.following.count }} followers</b></span> .
    <span><b>{{ user.followers.count }} following</b></span>
    {% if request.user == user %}
    <!-- edit profile and share btn -->
    <div class="mt-3">
        <a href="#" class="main-btn btn ps-3 pt-2 pb-2 pe-3 text-black ms-1"><b>Share</b></a>
        <a href="{% url 'accounts:edit_profile' %}" class="main-btn btn ps-3 pt-2 pb-2 pe-3 text-black ms-1"><b>Edit Profile</b></a>
    </div>
    {% elif is_following %}
    <div class="mt-3">
        <a href="#" class="main-btn btn ps-3 pt-2 pb-2 pe-3 text-black ms-4"><b>Message</b></a>
        <a href="{% url 'accounts:unfollow' user.username %}" class="following-btn btn ps-3 pt-2 pb-2 pe-3 text-white ms-1 me-4"><b>Following</b></a>
        <a href="#">
            <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" class="gUZ pBj U9O kVc" height="20" width="20" viewBox="0 0 24 24" aria-hidden="true" aria-label="" role="img">
                <path d="M12 9c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3M3 9c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3zm18 0c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3z" fill="#111111" stroke-width="0px"></path>
            </svg>
        </a>
    </div>
    {% else %}
    <div class="mt-3">
        <a href="#" class="main-btn btn ps-3 pt-2 pb-2 pe-3 text-black ms-4"><b>Message</b></a>
        <a href="{% url 'accounts:follow' user.username %}" class="red-btn btn ps-3 pt-2 pb-2 pe-3 text-white ms-1 me-4">
            <b>Follow</b>
        </a>
        <a href="#">
            <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" class="gUZ pBj U9O kVc" height="20" width="20" viewBox="0 0 24 24" aria-hidden="true" aria-label="" role="img">
                <path 
                    d="M12 9c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3M3 9c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3zm18 0c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3z"
                    fill="#111111"
                    stroke-width="0px">
                </path>
            </svg>
        </a>
    </div>
    {% endif %}
    <!-- saved and created tab -->
    <div class="mt-5 mb-5">
        {% if '/_saved/' in request.get_full_path  %}
        <a href="{% url 'pins:created_pins' user.username %}" class="btn ps-3 pt-2 pb-2 pe-3 text-black ms-1">
            <b>Created</b>
        </a>
        <a href="{% url 'accounts:profile' user.username %}" class="btn-select-border text-decoration-none ps-3 pt-2 pb-2 pe-3 text-black ms-1">
            <b>Saved</b>
        </a>
        {% else %}
        <a href="{% url 'pins:created_pins' user.username %}" class="btn-select-border text-decoration-none ps-3 pt-2 pb-2 pe-3 text-black ms-1">
            <b>Created</b>
        </a>
        <a href="{% url 'accounts:profile' user.username %}" class="btn ps-3 pt-2 pb-2 pe-3 text-black ms-1">
            <b>Saved</b>
        </a>
        {% endif %}
    </div>
    <!-- create board modal -->
    <div id="simpleModal" class="modal">
        <div class="modal-content ps-5 pb-5 pe-5">
            <h3 class="mt-4 mb-3"><b>Create Board</b></h3>
            <div class="row">
                <form method="post" action="{% url 'boards:create_board' %}">
                    {% csrf_token %}
                    <label style="float: left;" for="">Name</label>
                    {{ create_board_form.title }}                        
                    <div class="col-md-1 mt-4">    
                        {{ create_board_form.is_private }}                        
                    </div>
                    <div style="text-align:left" class="col-md-11">
                        <b class="ms-1">Keep this board secret</b>
                        <p class="text-muted ms-4">So only you and collaborators can see it. Learm more</p>
                    </div>
                    <input class="modal-red-btn btn text-white mt-3" type="submit" value="create">
                </form>
            </div>
        </div>
    </div>
    {% if '_saved' in request.get_full_path %}
    <!-- user boards -->
    <div id="boards" class="row">
        {% for board in boards %}
            {% if request.user != user %}
                <!-- do not show private boards to people -->
                {% if not board.is_private %}
                    <div class="col-md-2 ms-2 me-4 mb-2">
                        <a href="{% url 'boards:board_detail' username=board.user.username board_name=board.title %}">
                            <img style="object-fit: cover; border-radius: 20px;" height="200" width="200" src="{{ board.cover.url }}">
                            <h4 class="mt-2 text-black" style="float: left;"><b>{{ board.title }}</b></h4>
                        </a>
                    </div>  
                {% endif %}
                {% elif request.user == user %}
                    <div class="col-md-2 ms-2 me-4 mb-2">
                        <a href="{% url 'boards:board_detail' username=board.user.username board_name=board.title %}">
                            <img style="object-fit: cover; border-radius: 20px;" height="200" width="200" src="{{ board.cover.url }}">
                            <h4 class="mt-2 text-black" style="float: left;  overflow: hidden;"><b>{{ board.title }}</b></h4>
                        </a>
                        <a style="float: right;" href="{% url 'boards:edit_board' board.id %}">
                            <div class="mb-2"></div>
                            <svg class="main-btn p-1 rounded-circle" class="gUZ pBj U9O kVc" height="25" width="25" viewBox="0 0 24 24" aria-hidden="true" aria-label="" role="img">
                                <path d="m13.386 6.018 4.596 4.596L7.097 21.499 1 22.999l1.501-6.096L13.386 6.018zm8.662-4.066a3.248 3.248 0 0 1 0 4.596l-2.298 2.3-4.596-4.598 2.298-2.299a3.248 3.248 0 0 1 4.596 0z"></path>
                            </svg>
                        </a>
                    </div>  
                {% endif %}
        {% endfor %}
    </div>
    {% else %}
    <!-- user created pins -->
    <div class="row">
        {% for pin in created_pins %}
        <div class="img-container col-md-2 ms-2 me-4 mb-3">
            <a href="{% url 'pins:pin_detail' pin.id %}">
                {% if pin.get_type == 'video' %}
                    <video autoplay muted loop class="video" >
                        <source src="{{ pin.file.url }}" >
                    </video>
                {% elif pin.get_type == 'image' %}
                    <img style="object-fit: cover; border-radius: 20px; cursor: zoom-in;" height="300" width="200" src="{{ pin.file.url }}">
                {% endif %}
            </a>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}

accounts/templates/register.html
{% load static %}
<!DOCTYPE html>
<head>
    <!-- bootstrap css cdn -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Pinterest</title>
</head>
{% include 'first_header.html' %}
<body class="login-bg" style="height: 100vh;">
    <div class="modal-content ps-5 pb-5 pe-5">
        <h3 class="mt-4 mb-3"><b>Create account</b></h3>
        <div class="row">
            <form method="post">
                {% csrf_token %}
                <div class="">
                    {{ form.email }}
                </div>
                <div class="mt-2">
                    {{ form.username }}
                </div>
                <div class="mt-2">
                    {{ form.password }}
                </div>
                <input class="modal-red-btn btn text-white mt-3 w-100" type="submit" value="Submit">
            </form>
            <small class="text-muted mt-3">
                Already have a account? <a class="text-decoration-none" href="{% url 'accounts:user_login' %}">Login Here</a>
            </small>
        </div>
    </div>
</body>

</html>

accounts/templates/verify_email.html
{% extends 'login.html' %}
 {% block content %}
    <h1>Thank you for signing up!</h1>
    <p>Please check your email and follow the instructions to activate your account.</p>
{% endblock %}